Display ‘shortName’ for Case of the Week block/API call
parameter1/science-medicine-group-newsletters pull request #20
Opened 2023-05-02 18:17 UTC by jwade1327

DEV:
<img width="825" alt="Screen Shot 2023-05-02 at 1 14 19 PM" src="https://user-images.githubusercontent.com/64623209/235751193-48551b68-d429-4819-9927-43329ed9fd61.png">
PROD: 
<img width="715" alt="Screen Shot 2023-05-02 at 1 17 36 PM" src="https://user-images.githubusercontent.com/64623209/235751275-83f155cc-0325-4b6a-94c8-a207b6533d04.png">

2023-05-02 18:17 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Case of the Week block in newsletter to pull in title vs description](https://trello.com/c/XIKSkdp9/274-update-case-of-the-week-block-in-newsletter-to-pull-in-title-vs-description)

2023-05-02 20:26 UTC, Shinsina requested changes

2023-05-02 20:26 UTC, Shinsina commented on packages/common/components/blocks/external-api.marko
> +$ const { apiUrl, shortName, ctaLinkStyle } = input;
I don't believe this is used in this file or `common-content-api-list-item-block` via it's `input` unless I'm misunderstanding something here?

2023-05-05 13:46 UTC, Shinsina approved these changes

2023-05-05 13:46 UTC, merged