Add new Footer to DrB LFTE
parameter1/science-medicine-group-newsletters pull request #61
Opened 2024-02-01 19:16 UTC by jwade1327

<img width="741" alt="Screen Shot 2024-02-01 at 1 12 37 PM" src="https://github.com/parameter1/science-medicine-group-newsletters/assets/64623209/1e79ed8b-06ec-47e3-abe8-d0e1630ef843">
<img width="1024" alt="Screen Shot 2024-02-01 at 1 12 47 PM" src="https://github.com/parameter1/science-medicine-group-newsletters/assets/64623209/ad547b26-40a2-4064-af51-7e366dfcb6cc">

2024-02-01 19:16 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change the DrBicuspid LFTE template footer.](https://trello.com/c/qGTQq7uy/523-change-the-drbicuspid-lfte-template-footer)

2024-02-01 20:22 UTC, Shinsina requested changes

2024-02-01 20:22 UTC, Shinsina commented on packages/common/components/blocks/marko.json
> +    "template": "footer-new.marko"
Nit picky as all get out but this should probably be `common-new-footer-block`

2024-02-02 16:02 UTC, Shinsina approved these changes

2024-02-02 16:02 UTC, merged