Add UTM parameter to newsletters
parameter1/science-medicine-group-newsletters pull request #97
Opened 2024-12-05 18:49 UTC by jwade1327

Source: https://www.braze.com/docs/user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events#email-clicks-events/

Not sure how to test this, but here's my best stab at it.

2024-12-05 18:49 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add UTM Params on newsletter links](https://trello.com/c/N47AryAZ/671-add-utm-params-on-newsletter-links)

2024-12-09 18:58 UTC, solocommand requested changes
@jwade1327 a few things here:
1. You want the [liquid templating reference](https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags/#summary-of-supported-tags:~:text=%7B%7Bwhats_app.%24%7Binbound_media_urls%7D%7D%7D-,Campaign%20Attributes,-%7B%7Bcampaign.%24%7Bapi_id%7D%7D%7D), not the click message event docs. Specifically, I believe you need `{{campaign.${message_api_id}}}`.
2. We already have a [utility](https://github.com/parameter1/science-medicine-group-newsletters/blob/main/packages/common/utils/build-link-url.js) in this repo to modify links and inject the Braze user data, this should be updated to include whatever new params are required. No need to create a global wrapping component for marko-web-query to do this!
3. For SMG/Braze, the campaign name will _always_ be `[sitename] API Campaign`. This is likely not what is wanted here...what values are supposed to be injected?

2024-12-10 16:03 UTC, jwade1327 commented
@solocommand I couldn't find anything related to time/date other than start_date and end_date but that didn't seem to fint

2024-12-18 14:15 UTC, B77Mills approved these changes

2024-12-18 20:48 UTC, merged